//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.05 at 10:10:27 PM CEST 
//


package com.automaterijal.application.tecdoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for axleDetailsById2Record complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="axleDetailsById2Record"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://server.cat.tecdoc.net}axleDetailsById2RecordSrc"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="axleBodyType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="axleBodyTypeId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="axleDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="axleId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="axleLoadFrom" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="axleLoadTo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="axleManufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="axleModel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="axleStyle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="axleStyleId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="axleType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="axleTypeId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="brakeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="brakeTypeId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="driveHeightFrom" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="driveHeightTo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="hubSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="trackGauge" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="wheelMount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="wheelMountId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="yearOfConstrFrom" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="yearOfConstrTo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "axleDetailsById2Record", propOrder = {
    "axleBodyType",
    "axleBodyTypeId",
    "axleDescription",
    "axleId",
    "axleLoadFrom",
    "axleLoadTo",
    "axleManufacturer",
    "axleModel",
    "axleStyle",
    "axleStyleId",
    "axleType",
    "axleTypeId",
    "brakeType",
    "brakeTypeId",
    "driveHeightFrom",
    "driveHeightTo",
    "hubSystem",
    "trackGauge",
    "wheelMount",
    "wheelMountId",
    "yearOfConstrFrom",
    "yearOfConstrTo"
})
public class AxleDetailsById2Record
    extends AxleDetailsById2RecordSrc
{

    protected String axleBodyType;
    protected Integer axleBodyTypeId;
    protected String axleDescription;
    protected Long axleId;
    protected Integer axleLoadFrom;
    protected Integer axleLoadTo;
    protected String axleManufacturer;
    protected String axleModel;
    protected String axleStyle;
    protected Integer axleStyleId;
    protected String axleType;
    protected Integer axleTypeId;
    protected String brakeType;
    protected Integer brakeTypeId;
    protected Integer driveHeightFrom;
    protected Integer driveHeightTo;
    protected String hubSystem;
    protected Integer trackGauge;
    protected String wheelMount;
    protected Integer wheelMountId;
    protected Integer yearOfConstrFrom;
    protected Integer yearOfConstrTo;

    /**
     * Gets the value of the axleBodyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAxleBodyType() {
        return axleBodyType;
    }

    /**
     * Sets the value of the axleBodyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAxleBodyType(String value) {
        this.axleBodyType = value;
    }

    /**
     * Gets the value of the axleBodyTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAxleBodyTypeId() {
        return axleBodyTypeId;
    }

    /**
     * Sets the value of the axleBodyTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAxleBodyTypeId(Integer value) {
        this.axleBodyTypeId = value;
    }

    /**
     * Gets the value of the axleDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAxleDescription() {
        return axleDescription;
    }

    /**
     * Sets the value of the axleDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAxleDescription(String value) {
        this.axleDescription = value;
    }

    /**
     * Gets the value of the axleId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAxleId() {
        return axleId;
    }

    /**
     * Sets the value of the axleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAxleId(Long value) {
        this.axleId = value;
    }

    /**
     * Gets the value of the axleLoadFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAxleLoadFrom() {
        return axleLoadFrom;
    }

    /**
     * Sets the value of the axleLoadFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAxleLoadFrom(Integer value) {
        this.axleLoadFrom = value;
    }

    /**
     * Gets the value of the axleLoadTo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAxleLoadTo() {
        return axleLoadTo;
    }

    /**
     * Sets the value of the axleLoadTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAxleLoadTo(Integer value) {
        this.axleLoadTo = value;
    }

    /**
     * Gets the value of the axleManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAxleManufacturer() {
        return axleManufacturer;
    }

    /**
     * Sets the value of the axleManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAxleManufacturer(String value) {
        this.axleManufacturer = value;
    }

    /**
     * Gets the value of the axleModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAxleModel() {
        return axleModel;
    }

    /**
     * Sets the value of the axleModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAxleModel(String value) {
        this.axleModel = value;
    }

    /**
     * Gets the value of the axleStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAxleStyle() {
        return axleStyle;
    }

    /**
     * Sets the value of the axleStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAxleStyle(String value) {
        this.axleStyle = value;
    }

    /**
     * Gets the value of the axleStyleId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAxleStyleId() {
        return axleStyleId;
    }

    /**
     * Sets the value of the axleStyleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAxleStyleId(Integer value) {
        this.axleStyleId = value;
    }

    /**
     * Gets the value of the axleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAxleType() {
        return axleType;
    }

    /**
     * Sets the value of the axleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAxleType(String value) {
        this.axleType = value;
    }

    /**
     * Gets the value of the axleTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAxleTypeId() {
        return axleTypeId;
    }

    /**
     * Sets the value of the axleTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAxleTypeId(Integer value) {
        this.axleTypeId = value;
    }

    /**
     * Gets the value of the brakeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrakeType() {
        return brakeType;
    }

    /**
     * Sets the value of the brakeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrakeType(String value) {
        this.brakeType = value;
    }

    /**
     * Gets the value of the brakeTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrakeTypeId() {
        return brakeTypeId;
    }

    /**
     * Sets the value of the brakeTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrakeTypeId(Integer value) {
        this.brakeTypeId = value;
    }

    /**
     * Gets the value of the driveHeightFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDriveHeightFrom() {
        return driveHeightFrom;
    }

    /**
     * Sets the value of the driveHeightFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDriveHeightFrom(Integer value) {
        this.driveHeightFrom = value;
    }

    /**
     * Gets the value of the driveHeightTo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDriveHeightTo() {
        return driveHeightTo;
    }

    /**
     * Sets the value of the driveHeightTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDriveHeightTo(Integer value) {
        this.driveHeightTo = value;
    }

    /**
     * Gets the value of the hubSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHubSystem() {
        return hubSystem;
    }

    /**
     * Sets the value of the hubSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHubSystem(String value) {
        this.hubSystem = value;
    }

    /**
     * Gets the value of the trackGauge property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTrackGauge() {
        return trackGauge;
    }

    /**
     * Sets the value of the trackGauge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTrackGauge(Integer value) {
        this.trackGauge = value;
    }

    /**
     * Gets the value of the wheelMount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWheelMount() {
        return wheelMount;
    }

    /**
     * Sets the value of the wheelMount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWheelMount(String value) {
        this.wheelMount = value;
    }

    /**
     * Gets the value of the wheelMountId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWheelMountId() {
        return wheelMountId;
    }

    /**
     * Sets the value of the wheelMountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWheelMountId(Integer value) {
        this.wheelMountId = value;
    }

    /**
     * Gets the value of the yearOfConstrFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYearOfConstrFrom() {
        return yearOfConstrFrom;
    }

    /**
     * Sets the value of the yearOfConstrFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYearOfConstrFrom(Integer value) {
        this.yearOfConstrFrom = value;
    }

    /**
     * Gets the value of the yearOfConstrTo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYearOfConstrTo() {
        return yearOfConstrTo;
    }

    /**
     * Sets the value of the yearOfConstrTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYearOfConstrTo(Integer value) {
        this.yearOfConstrTo = value;
    }

}
