//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.05 at 10:10:27 PM CEST 
//


package com.automaterijal.application.tecdoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for criteriaDialogAttributsRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="criteriaDialogAttributsRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://server.cat.tecdoc.net}criteriaDialogAttributsRequestSrc"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="articleCountry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="articleIds" type="{http://server.cat.tecdoc.net}articleIdPairSeq" minOccurs="0"/&gt;
 *         &lt;element name="attributeIds" type="{http://server.cat.tecdoc.net}integerList" minOccurs="0"/&gt;
 *         &lt;element name="attributeValues" type="{http://server.cat.tecdoc.net}attributeValueSeq" minOccurs="0"/&gt;
 *         &lt;element name="brandNo" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="genericArticleId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="lang" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="linkingTargetId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="linkingTargetType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="provider" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="requestMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "criteriaDialogAttributsRequest", propOrder = {
    "articleCountry",
    "articleIds",
    "attributeIds",
    "attributeValues",
    "brandNo",
    "genericArticleId",
    "lang",
    "linkingTargetId",
    "linkingTargetType",
    "provider",
    "requestMode"
})
public class CriteriaDialogAttributsRequest
    extends CriteriaDialogAttributsRequestSrc
{

    protected String articleCountry;
    protected ArticleIdPairSeq articleIds;
    protected IntegerList attributeIds;
    protected AttributeValueSeq attributeValues;
    protected Long brandNo;
    protected long genericArticleId;
    protected String lang;
    protected Long linkingTargetId;
    protected String linkingTargetType;
    protected int provider;
    protected String requestMode;

    /**
     * Gets the value of the articleCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArticleCountry() {
        return articleCountry;
    }

    /**
     * Sets the value of the articleCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArticleCountry(String value) {
        this.articleCountry = value;
    }

    /**
     * Gets the value of the articleIds property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleIdPairSeq }
     *     
     */
    public ArticleIdPairSeq getArticleIds() {
        return articleIds;
    }

    /**
     * Sets the value of the articleIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleIdPairSeq }
     *     
     */
    public void setArticleIds(ArticleIdPairSeq value) {
        this.articleIds = value;
    }

    /**
     * Gets the value of the attributeIds property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerList }
     *     
     */
    public IntegerList getAttributeIds() {
        return attributeIds;
    }

    /**
     * Sets the value of the attributeIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerList }
     *     
     */
    public void setAttributeIds(IntegerList value) {
        this.attributeIds = value;
    }

    /**
     * Gets the value of the attributeValues property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeValueSeq }
     *     
     */
    public AttributeValueSeq getAttributeValues() {
        return attributeValues;
    }

    /**
     * Sets the value of the attributeValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeValueSeq }
     *     
     */
    public void setAttributeValues(AttributeValueSeq value) {
        this.attributeValues = value;
    }

    /**
     * Gets the value of the brandNo property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBrandNo() {
        return brandNo;
    }

    /**
     * Sets the value of the brandNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBrandNo(Long value) {
        this.brandNo = value;
    }

    /**
     * Gets the value of the genericArticleId property.
     * 
     */
    public long getGenericArticleId() {
        return genericArticleId;
    }

    /**
     * Sets the value of the genericArticleId property.
     * 
     */
    public void setGenericArticleId(long value) {
        this.genericArticleId = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the linkingTargetId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLinkingTargetId() {
        return linkingTargetId;
    }

    /**
     * Sets the value of the linkingTargetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLinkingTargetId(Long value) {
        this.linkingTargetId = value;
    }

    /**
     * Gets the value of the linkingTargetType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkingTargetType() {
        return linkingTargetType;
    }

    /**
     * Sets the value of the linkingTargetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkingTargetType(String value) {
        this.linkingTargetType = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     */
    public int getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     */
    public void setProvider(int value) {
        this.provider = value;
    }

    /**
     * Gets the value of the requestMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestMode() {
        return requestMode;
    }

    /**
     * Sets the value of the requestMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestMode(String value) {
        this.requestMode = value;
    }

}
