//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.27 at 11:03:50 AM CET 
//


package com.automaterijal.application.tecdoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for criteriaDialogAttributsRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="criteriaDialogAttributsRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://server.cat.tecdoc.net}criteriaDialogAttributsRecordSrc"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="articleLinkIds" type="{http://server.cat.tecdoc.net}articleLinkPairSeq" minOccurs="0"/&gt;
 *         &lt;element name="attributeValues" type="{http://server.cat.tecdoc.net}attributeValueSeq" minOccurs="0"/&gt;
 *         &lt;element name="attributes" type="{http://server.cat.tecdoc.net}attributeSeq" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "criteriaDialogAttributsRecord", propOrder = {
    "articleLinkIds",
    "attributeValues",
    "attributes"
})
public class CriteriaDialogAttributsRecord
    extends CriteriaDialogAttributsRecordSrc
{

    protected ArticleLinkPairSeq articleLinkIds;
    protected AttributeValueSeq attributeValues;
    protected AttributeSeq attributes;

    /**
     * Gets the value of the articleLinkIds property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleLinkPairSeq }
     *     
     */
    public ArticleLinkPairSeq getArticleLinkIds() {
        return articleLinkIds;
    }

    /**
     * Sets the value of the articleLinkIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleLinkPairSeq }
     *     
     */
    public void setArticleLinkIds(ArticleLinkPairSeq value) {
        this.articleLinkIds = value;
    }

    /**
     * Gets the value of the attributeValues property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeValueSeq }
     *     
     */
    public AttributeValueSeq getAttributeValues() {
        return attributeValues;
    }

    /**
     * Sets the value of the attributeValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeValueSeq }
     *     
     */
    public void setAttributeValues(AttributeValueSeq value) {
        this.attributeValues = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSeq }
     *     
     */
    public AttributeSeq getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSeq }
     *     
     */
    public void setAttributes(AttributeSeq value) {
        this.attributes = value;
    }

}
