//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.31 at 11:12:31 AM CET 
//


package com.automaterijal.application.tecdoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for csgDocumentDataByArticleId2Record complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="csgDocumentDataByArticleId2Record"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://server.cat.tecdoc.net}csgDocumentDataByArticleId2RecordSrc"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="articleDoc" type="{http://server.cat.tecdoc.net}articleDocumentsByDocIdRecord" minOccurs="0"/&gt;
 *         &lt;element name="coSeq" type="{http://server.cat.tecdoc.net}coordinatesByArticleDocumentRecordSeq" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "csgDocumentDataByArticleId2Record", propOrder = {
    "articleDoc",
    "coSeq"
})
public class CsgDocumentDataByArticleId2Record
    extends CsgDocumentDataByArticleId2RecordSrc
{

    protected ArticleDocumentsByDocIdRecord articleDoc;
    protected CoordinatesByArticleDocumentRecordSeq coSeq;

    /**
     * Gets the value of the articleDoc property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleDocumentsByDocIdRecord }
     *     
     */
    public ArticleDocumentsByDocIdRecord getArticleDoc() {
        return articleDoc;
    }

    /**
     * Sets the value of the articleDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleDocumentsByDocIdRecord }
     *     
     */
    public void setArticleDoc(ArticleDocumentsByDocIdRecord value) {
        this.articleDoc = value;
    }

    /**
     * Gets the value of the coSeq property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinatesByArticleDocumentRecordSeq }
     *     
     */
    public CoordinatesByArticleDocumentRecordSeq getCoSeq() {
        return coSeq;
    }

    /**
     * Sets the value of the coSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinatesByArticleDocumentRecordSeq }
     *     
     */
    public void setCoSeq(CoordinatesByArticleDocumentRecordSeq value) {
        this.coSeq = value;
    }

}
