//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.31 at 11:12:31 AM CET 
//


package com.automaterijal.application.tecdoc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for matchesByVINRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="matchesByVINRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://server.cat.tecdoc.net}matchesByVINRecordSrc"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="matchingManufacturers" type="{http://server.cat.tecdoc.net}matchingManufacturersByVINRecordSeq"/&gt;
 *         &lt;element name="matchingModels" type="{http://server.cat.tecdoc.net}matchingVehicleModelSeriesByVINRecordSeq"/&gt;
 *         &lt;element name="matchingVehicles" type="{http://server.cat.tecdoc.net}matchingVehicleIdsByVINRecordSeq"/&gt;
 *         &lt;element name="matchingVehiclesCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="dataSource" type="{http://server.cat.tecdoc.net}getVehiclesByVINDataSource" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "matchesByVINRecord", propOrder = {
    "matchingManufacturers",
    "matchingModels",
    "matchingVehicles",
    "matchingVehiclesCount",
    "dataSource"
})
public class MatchesByVINRecord
    extends MatchesByVINRecordSrc
{

    @XmlElement(required = true)
    protected MatchingManufacturersByVINRecordSeq matchingManufacturers;
    @XmlElement(required = true)
    protected MatchingVehicleModelSeriesByVINRecordSeq matchingModels;
    @XmlElement(required = true)
    protected MatchingVehicleIdsByVINRecordSeq matchingVehicles;
    protected int matchingVehiclesCount;
    protected List<GetVehiclesByVINDataSource> dataSource;

    /**
     * Gets the value of the matchingManufacturers property.
     * 
     * @return
     *     possible object is
     *     {@link MatchingManufacturersByVINRecordSeq }
     *     
     */
    public MatchingManufacturersByVINRecordSeq getMatchingManufacturers() {
        return matchingManufacturers;
    }

    /**
     * Sets the value of the matchingManufacturers property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchingManufacturersByVINRecordSeq }
     *     
     */
    public void setMatchingManufacturers(MatchingManufacturersByVINRecordSeq value) {
        this.matchingManufacturers = value;
    }

    /**
     * Gets the value of the matchingModels property.
     * 
     * @return
     *     possible object is
     *     {@link MatchingVehicleModelSeriesByVINRecordSeq }
     *     
     */
    public MatchingVehicleModelSeriesByVINRecordSeq getMatchingModels() {
        return matchingModels;
    }

    /**
     * Sets the value of the matchingModels property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchingVehicleModelSeriesByVINRecordSeq }
     *     
     */
    public void setMatchingModels(MatchingVehicleModelSeriesByVINRecordSeq value) {
        this.matchingModels = value;
    }

    /**
     * Gets the value of the matchingVehicles property.
     * 
     * @return
     *     possible object is
     *     {@link MatchingVehicleIdsByVINRecordSeq }
     *     
     */
    public MatchingVehicleIdsByVINRecordSeq getMatchingVehicles() {
        return matchingVehicles;
    }

    /**
     * Sets the value of the matchingVehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchingVehicleIdsByVINRecordSeq }
     *     
     */
    public void setMatchingVehicles(MatchingVehicleIdsByVINRecordSeq value) {
        this.matchingVehicles = value;
    }

    /**
     * Gets the value of the matchingVehiclesCount property.
     * 
     */
    public int getMatchingVehiclesCount() {
        return matchingVehiclesCount;
    }

    /**
     * Sets the value of the matchingVehiclesCount property.
     * 
     */
    public void setMatchingVehiclesCount(int value) {
        this.matchingVehiclesCount = value;
    }

    /**
     * Gets the value of the dataSource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataSource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetVehiclesByVINDataSource }
     * 
     * 
     */
    public List<GetVehiclesByVINDataSource> getDataSource() {
        if (dataSource == null) {
            dataSource = new ArrayList<GetVehiclesByVINDataSource>();
        }
        return this.dataSource;
    }

}
