//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.04 at 11:53:31 AM CEST 
//


package com.automaterijal.application.tecdoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for responseData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="responseData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "responseData")
@XmlSeeAlso({
    OEArticlesByVINResponseSrc.class,
    LinkageTargetsResponseSrc.class,
    ArticlesResponseSrc.class,
    VersionResponseSrc.class,
    AutoCompleteSuggestionsResponseSrc.class,
    VehicleDataByVINExtResponseSrc.class,
    PartsByVINExtResponseSrc.class,
    VehiclesByVINResponseSrc.class,
    AmBrandAddressResponseSrc.class,
    LanguagesResponseSrc.class,
    LinkedArticlesResponseSrc.class,
    LinkedBrandsResponseSrc.class,
    CountriesResponseSrc.class,
    CountryGroupsResponseSrc.class,
    Criteria2ResponseSrc.class,
    GenericArticlesResponseSrc.class,
    VehicleIdsByKTypeNumberResponseSrc.class,
    VehicleIdsByMotor2ResponseSrc.class,
    VehicleIdsByMarkResponseSrc.class,
    VehicleIdsByVendorId2ResponseSrc.class,
    VehicleIdsByKeyNumberPlates3ResponseSrc.class,
    AxleBrakeSizesResponseSrc.class,
    AxleIdByTypeManCriteria3ResponseSrc.class,
    AxleKeyNumbersResponseSrc.class,
    AxleIdByKeyNumberResponseSrc.class,
    AxleByIds2ResponseSrc.class,
    AxleByIds3ResponseSrc.class,
    MotorIdsByManuIdCriteria2ResponseSrc.class,
    MotorsByCarTypeManuIdTerm2ResponseSrc.class,
    MotorByIds2ResponseSrc.class,
    MotorByIds3ResponseSrc.class,
    VendorIds2ResponseSrc.class,
    MarkByIdResponseSrc.class,
    ShortCuts2ResponseSrc.class,
    ChildNodesAllLinkingTarget2ResponseSrc.class,
    ChildNodesPatternResponseSrc.class,
    ChildNodesPattern2ResponseSrc.class,
    GenericArticlesByManufacturer6ResponseSrc.class,
    GenericArticlesByManufacturer7ResponseSrc.class,
    ArticleAccessoryList4ResponseSrc.class,
    ArticleLinkedAllLinkingTargetManufacturerResponseSrc.class,
    ArticleLinkedAllLinkingTargetManufacturer2ResponseSrc.class,
    AmBrandsResponseSrc.class,
    BrandsResponseSrc.class,
    VehicleByIds3ResponseSrc.class,
    VehicleByIds4ResponseSrc.class,
    VehiclesByKeyNumberPlatesResponseSrc.class,
    ArticleIdsWithStateResponseSrc.class,
    ArticlesByIds4ResponseSrc.class,
    ArticleDirectSearchAllNumbersWithStateResponseSrc.class,
    CriteriaDialogAttributsResponseSrc.class,
    ArticleLinkedAllLinkingTarget3ResponseSrc.class,
    ArticleLinkedAllLinkingTarget4ResponseSrc.class,
    ArticleLinkedAllLinkingTargetsByIds3ResponseSrc.class,
    ModelSeriesResponseSrc.class,
    ModelSeries2ResponseSrc.class,
    VehicleIdsByCriteriaResponseSrc.class,
    ArticlePartListResponseSrc.class,
    ArticlesByIds6ResponseSrc.class,
    ArticlesByIds7ResponseSrc.class,
    KeyValuesResponseSrc.class,
    ManufacturersResponseSrc.class,
    Manufacturers2ResponseSrc.class
})
public abstract class ResponseData {


}
