//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.31 at 11:12:31 AM CET 
//


package com.automaterijal.application.tecdoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RmiEngineCodesDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RmiEngineCodesDescription"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rmiEngineCodeId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="rmiEngineCodeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RmiEngineCodesDescription", propOrder = {
    "rmiEngineCodeId",
    "rmiEngineCodeDescription"
})
public class RmiEngineCodesDescription {

    protected int rmiEngineCodeId;
    @XmlElement(required = true)
    protected String rmiEngineCodeDescription;

    /**
     * Gets the value of the rmiEngineCodeId property.
     * 
     */
    public int getRmiEngineCodeId() {
        return rmiEngineCodeId;
    }

    /**
     * Sets the value of the rmiEngineCodeId property.
     * 
     */
    public void setRmiEngineCodeId(int value) {
        this.rmiEngineCodeId = value;
    }

    /**
     * Gets the value of the rmiEngineCodeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRmiEngineCodeDescription() {
        return rmiEngineCodeDescription;
    }

    /**
     * Sets the value of the rmiEngineCodeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRmiEngineCodeDescription(String value) {
        this.rmiEngineCodeDescription = value;
    }

}
